apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kube-vip-cloud-provider.name" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
spec:
  serviceName: {{ include "kube-vip-cloud-provider.name" . }}
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-vip-cloud-provider.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - command:
            - /kube-vip-cloud-provider
            - --leader-elect-resource-name=kube-vip-cloud-controller
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          name: {{ include "kube-vip-cloud-provider.name" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
          - name: KUBEVIP_NAMESPACE
            value: {{ .Release.Namespace | default "kube-system" | quote }}
          {{- if .Values.config.kubeVipCloudConfig }}
          - name: KUBEVIP_CONFIG_MAP
            value: {{ .Values.config.kubeVipCloudConfig | quote }}
          {{- end }}
          {{- if .Values.config.destinationCIDR }}
          - name: KUBEVIP_SERVICE_CIDR
            value: {{ .Values.config.destinationCIDR | quote }}
          {{- end }}
      serviceAccountName: {{ include "kube-vip-cloud-provider.name" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
